export const PLAYER_SAVE_BASE = 'PLAYER_SAVE_BASE';
export const PLAYER_SAVE_AGENT = 'PLAYER_SAVE_AGENT';
export const PLAYER_SAVE_RECORD = 'PLAYER_SAVE_RECORD';
export const PLAYER_SAVE_RECORDITEM = 'PLAYER_SAVE_RECORDITEM';
export const PLAYER_SAVE_PIC = 'PLAYER_SAVE_PIC';
export const PLAYER_SAVE_OTHER = 'PLAYER_SAVE_OTHER';
export const WEIXIN_SAVE_USER = 'WEIXIN_SAVE_USER';
